name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Instalar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restaurar dependências
      run: dotnet restore

    - name: Compilar
      run: dotnet build --no-restore --configuration Release

    - name: Rodar testes
      run: dotnet test --no-build --configuration Release --verbosity normal